### ISSUE TITLE
Modal - вечный ререндер (переполненение стека) на граничных случаях появления скролла (useLayoutEffect)

### ISSUE THREAD

**Issue by crutch12** [AdmiralDS/react-ui#1189]
В Modal происходит вечный вызов useLayoutEffect, из-за чего React падает с ошибкой 185

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
  at ri (/react-ui/5767.ee544824.iframe.bundle.js:401:735368))
  at /react-ui/components-Modal-stories-Modal-stories.7cd98139.iframe.bundle.js:1:92319
  at Rj (/react-ui/5767.ee544824.iframe.bundle.js:401:760391))
  at lk (/react-ui/5767.ee544824.iframe.bundle.js:401:767592))
  at jk (/react-ui/5767.ee544824.iframe.bundle.js:401:767441))
  at ik (/react-ui/5767.ee544824.iframe.bundle.js:401:766992))
  at Xk (/react-ui/5767.ee544824.iframe.bundle.js:401:778638))
  at Qk (/react-ui/5767.ee544824.iframe.bundle.js:401:779161))
  at Fk (/react-ui/5767.ee544824.iframe.bundle.js:401:772971))
```

**Условия воспроизведения:**
Admiral v7.5.0 (latest)
Браузер - Google Chrome 119.0.6045.160 (встречается на всех версиях)
ОС - win 11

Алгоритм
1) https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-modal--docs
2) Выставляем масштаб 67%,, высота окна 1221px, ширина - неважно, но >1000px
3) Идём к **Modal. Пример со скроллом**
4) Жмём **Open modal with scrollable content**
5) Готово! Ловим вечный ререндер и переполнение стека

**Comment by DrUNE** [comment]
Спасибо, не просто было поймать ситуацию в которой это проявлялось
